## Практическое задание. Часть №1

In [1]:
import numpy as np

__1. Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:__

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

__в) матрица определена, с размерностью 8х8__  
__г) матрица определена, с размерностью 4х4__

__2. Найти сумму и произведение матриц
$A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$__

In [2]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

__Сумма__

A + B = 
$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} +
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ = 
$\begin{pmatrix}
1 + 4 & -2 + (-1)\\ 
3 + 0 & 0 + 5
\end{pmatrix}$ = 
$\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

In [3]:
a + b

array([[ 5, -3],
       [ 3,  5]])

__Произведение__

A * B = 
$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} *
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ = 
$\begin{pmatrix}
1 * 4 + -2 * 0 & 1 * (-1) + (-2)* 5\\ 
3 * 4 + 0 * 0 & 3 * (-1) + 0 * 5 
\end{pmatrix}$ = 
$\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

In [4]:
a.dot(b)

array([[  4, -11],
       [ 12,  -3]])

__3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$__

$A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$  
  
$B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, 
  
$C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$  
  
$3\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 
2\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 
4\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = 
\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} - 
\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix} +
\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} = 
\begin{pmatrix}
3 - 0 + 8 & 21 - 10 -16\\ 
9 - 4 + 4 & -18 + 2 + 4
\end{pmatrix} = 
\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}
$

In [5]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])
3*a - 2*b + 4*c

array([[ 11,  -5],
       [  9, -12]])

__4. Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.__

In [6]:
a = np.array([[4, 1], [5, -2], [2, 3]])

$A^T=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}$

In [7]:
a.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

$AA^T = 
\begin{pmatrix}
4 * 4 + 1 * 1 & 4 * 5 + 1 * (-2) & 4 * 2 + 1 * 3\\ 
5 * 4 + (-2) * 1 & 5 * 5 + (-2) * (-2) & 5 * 2 + (-2) * 3\\ 
2 * 4 + 3 * 1 & 2 * 5 + 3 * (-2) & 2 * 2 + 3 * 3
\end{pmatrix} = 
\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}$

In [8]:
np.dot(a,a.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

$A^TA = 
\begin{pmatrix}
4 * 4 + 5 * 5 + 2 * 2 & 4 * 1 + 5 * (-2) + 2 * 3\\ 
1 * 4 + (-2) * 5 + 3 * 2 & 1 * 1 + (-2) * (-2) + 3 * 3\\ 
\end{pmatrix} = 
\begin{pmatrix}
45 & 0\\ 
0 & 14\\ 
\end{pmatrix}
$

In [9]:
np.dot(a.T, a)

array([[45,  0],
       [ 0, 14]])

__5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.__

## Практическое задание. Часть №2

In [10]:
import numpy.linalg as lg

__1. Вычислить определитель:__

   __a)__
$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$

$sinx * sinx - (-cosx) * cosx = sin^{2}x + cos^{2}x = 1$

   __б)__
$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$

$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} =
4\begin{vmatrix} 
5 & 1\\ 
0 & 9
\end{vmatrix} - 
2\begin{vmatrix} 
0 & 1\\ 
0 & 9
\end{vmatrix} + 
3\begin{vmatrix} 
0 & 5\\ 
0 & 0
\end{vmatrix} = 
4(5 * 9 - 1 * 0) - 2(0 * 9 - 1 * 0) + 3(0 * 0 - 5 * 0) = 4 * 45 = 180$

In [11]:
lg.det(np.array([[4,2,3], [0,5,1], [0,0,9]]))

180.0

__в)__
$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} =
1\begin{vmatrix} 
5 & 6\\ 
8 & 9
\end{vmatrix} - 
2\begin{vmatrix} 
4 & 6\\ 
7 & 9
\end{vmatrix} + 
3\begin{vmatrix} 
4 & 5\\ 
7 & 8
\end{vmatrix} = 
1 * (5 * 9 - 8 * 6) - 2(4 * 9 - 7 * 6) + 3(4 * 8 - 7 * 5) = 
-3 + 12 - 9 = 0$

In [12]:
lg.det(np.array([[1,2,3], [4,5,6], [7,8,9]]))

6.66133814775094e-16

__2. Определитель матрицы $A$ равен $4$. Найти:__

__а) $det(A^{2})$;__

Согласно свойству №9 - Для двух квадратных матриц одинакового размера  

$det(AB) = detA * detB$ => $det(A^2) = 4^2 = 16$

__б) $det(A^{T})$;__

Согласно свойству №1 - Определитель транспонированной матрицы равен определителю исходной:

$det(A^T) = det(A) = 4$

   __в) $det(2A)$.__

Согласно свойству №2 - Умножение строки или столбца матрицы на число  𝜆  приведет к умножению определителя матрицы на то же число.

$det(2A) = 2detA = 2*4 = 8$

__3.  Доказать, что матрица
$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$
вырожденная.__

Согласно свойству №11 - Если к одной из строк матрицы прибавить другую, умноженную на число, ее определитель не изменится

Поэтому можно прибавить ко второй строке первую умноженную на 2

$\begin{pmatrix}
-2 & 7 & -3\\ 
0 & 0 & 0\\ 
-3 & 7 & 13
\end{pmatrix}$

Если матрица имеет нулевую строку или столбец, то определитель равен нулю.

Матрица вырожденная т.к. определитель матрицы равен нулю

__4. Найти ранг матрицы:__

__а)__
$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

Третья строка является суммой первой и второй строк, значит её можно отбросить

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}$

Ранг матрицы равен 2

In [13]:
a = np.array([[1,2,3], [1,1,1], [2,3,4]])
print(f'Ранг матрицы равен {lg.matrix_rank(a)}')

Ранг матрицы равен 2


__б)__
$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Третья строка является суммой первой и второй строк, значит её можно отбросить

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$

Из второй строкb вычтем первую

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 0 & 1\\ 
2 & 3 & 5 & 6
\end{pmatrix}$

Ранг матрицы равен 3

In [17]:
a = np.array([[0,0,2,1], [0,0,2,2], [0,0,4,3], [2,3,5,6]])
print(f'Ранг матрицы равен {lg.matrix_rank(a)}')

Ранг матрицы равен 3
