In [4]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(precision=2, suppress=True)

In [2]:
def grid_arrow(x_1, y_1, x_2, y_2):
    fig = plt.figure()
    ax = fig.add_subplot(1,1,1)

    ax.spines['left'].set_position('zero')
    ax.spines['bottom'].set_position('zero')

    ax.spines['right'].set_color('none')
    ax.spines['top'].set_color('none')

    plt.axis('scaled')
    plt.xlim(-2,2)
    plt.ylim(-2,2)

    ax.arrow(0,0,x_1,y_1, head_width=0.15, head_length=0.2, length_includes_head=True, facecolor='black')
    ax.arrow(0,0,x_2,y_2, head_width=0.15, head_length=0.2, length_includes_head=True, facecolor='black')
    ax.annotate('e1', xy=(0.8, 0.3))
    ax.annotate('e2', xy=(0.6, 1.0))
    plt.show()

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

$$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0$$

$$(-1-\lambda)(6 - \lambda) + 12 = 0$$

$$-6 + \lambda - 6\lambda + \lambda^2 + 12 = 0$$

$$\lambda^2 - 5\lambda + 6 = 0$$

$$\lambda_1 + \lambda_2 = 5$$  
$$\lambda_1 \cdot \lambda_2 = 6$$

$$\lambda_1 = 2, \lambda_2 = 3$$

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

$$
\begin{cases}
-x_{1}-6x_{2}= 2x_{1}, \\
2x_{1}+6x_{2}= 2x_{2}.
\end{cases} =>
\begin{cases}
x_{1} = -2x_{2}, \\
x_{1} = -2x_{2}.
\end{cases}
$$ 

$$
\begin{cases}
-x_{1}-6x_{2}= 3x_{1}, \\
2x_{1}+6x_{2}= 3x_{2}.
\end{cases} =>
\begin{cases}
x_{1} = -1.5x_{2}, \\
x_{1} = -1.5x_{2}.
\end{cases}
$$ 

In [5]:
a = np.array([[-1,-6], [2,6]])
np.linalg.eig(a)

(array([2., 3.]),
 array([[-0.89,  0.83],
        [ 0.45, -0.55]]))

__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

$$\begin{vmatrix}
-1-\lambda & 0\\ 
0 & -1-\lambda
\end{vmatrix} = 0$$

$$(-1-\lambda)^2 = 0$$

$$\lambda = -1$$

$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

$$
\begin{cases}
-x_{1} = -x_{1}, \\
-x_{2} = -x_{2}.
\end{cases} =>
\begin{cases}
-x_{1} + x_{1} = 0, \\
-x_{2} + x_{2} = 0.
\end{cases} =>
\begin{cases}
0 = 0, \\
0 = 0.
\end{cases}
$$ 

Это означает что любой вектор является собственным для линейного оператора A

In [6]:
a = np.array([[-1,0], [0,-1]])
np.linalg.eig(a)

(array([-1., -1.]),
 array([[1., 0.],
        [0., 1.]]))

__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$$

$$\begin{cases}
2 = \lambda, \\
2 = \lambda.
\end{cases} =>
\begin{cases}
\lambda = 2, \\
\lambda = 2
\end{cases} => \lambda = 2
$$ 

Таким образом, вектор $x=(1,1)$ является собственным вектором линейного оператора, заданного матрицей $A$, и его собственное значение составляет $\lambda=2.$

In [11]:
a = np.array([[1,1], [-1,3]])
print(f'Cобственные значения: {np.linalg.eig(a)[0]}')

Cобственные значения: [2. 2.]


__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}.
$$

$$\begin{cases}
-9 = 3\lambda, \\
9 = -3\lambda,\\
-12 = -4\lambda
\end{cases} =>
\begin{cases}
\lambda = -3, \\
\lambda = -3,\\
\lambda = 3
\end{cases}
$$ 

Такая система не имеет смысла, следовательно, вектор $x=(3,-3,-4)$ не является собственным вектором линейного оператора, заданного матрицей $A$.

In [7]:
a = np.array([[0,3,0],[3,0,0],[0,0,3]])
np.linalg.eig(a)

(array([ 3., -3.,  3.]),
 array([[ 0.71, -0.71,  0.  ],
        [ 0.71,  0.71,  0.  ],
        [ 0.  ,  0.  ,  1.  ]]))